numbers = [5, 2, 1, 7, 4]
print(numbers)
numbers.insert(2, 6)
print(numbers)
numbers.remove(5)
print(numbers)
numbers.pop()
print(numbers)
numbers.index(7)
print(numbers.index(7))
print(50 in numbers)
print(6 in numbers)
numbers.append(6)
print(numbers)
print(numbers.count(6))
numbers.sort()
print(numbers)
numbers.reverse()
print(numbers)
numbers2 = numbers.copy()
numbers.append(10)
print(numbers2)
